In [1]:
import numpy as np

In [3]:
a = [1,2,3,'5']
a

[1, 2, 3, '5']

In [5]:
#numpy中的数组的数据类型一定要完全一致
b = np.array([4,5,'6'])
b

array(['4', '5', '6'], dtype='<U11')

In [6]:
c = np.array([4,5,6.0])
c

array([4., 5., 6.])

## 1）创建数组

In [7]:
#1.使用np.array
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [9]:
#2.使用np.arange,类似python中的range
b = np.arange(0,11,3)
b

array([0, 3, 6, 9])

In [11]:
#3.使用np.random模块
c = np.random.random()
c

0.32278388706190675

In [16]:
d = np.random.random((4,3)) #生成4行3列的随机数的数组
d

array([[0.46302205, 0.35649744, 0.13665015],
       [0.83948556, 0.31169902, 0.71760449],
       [0.01658788, 0.30431872, 0.99105665],
       [0.22189495, 0.94395695, 0.35095591]])

In [20]:
e = np.random.randint(0,100,size=(4,4))#生成4行4列的数组，值的范围0-100之间
e

array([[42, 28, 41, 72],
       [36, 69, 55, 51],
       [71, 69, 51, 92],
       [10, 27, 83, 67]])

In [21]:
#4.使用特殊函数生成

In [24]:
a1 = np.zeros((3,3))
a1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
a2 = np.ones((4,4))
a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
a3 = np.full((5,5),6)
a3

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [27]:
a4 = np.eye(7)
a4

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

总结
* 数组中的数据类型都是一致的
* 使用四种方法创建数组

## 2）数组数据类型dtype

In [1]:
import numpy as np

In [2]:
e = np.array([1,2,])
print(e)
print(e.dtype)

[1 2]
int32


In [3]:
f = np.array(['a','n'],dtype='U')
print(f)
print(f.dtype)

['a' 'n']
<U1


In [5]:
uf = f.astype('S')
print(uf)
print(uf.dtype)
print(f.dtype)

[b'a' b'n']
|S1
<U1


总结
1.
* numpy基于C语言编写，所以有很多数据类型
* numpy为了考虑处理海量数据的性能，针对不同的数据给不同的数据类型，来节省内存空间，所以有不同的数据类型
2.
* numpy数组的元素有多种数据类型
3.
* 用ndarray.astype修改数据类型

## 3）多维数组

In [36]:
import numpy as np

In [37]:
a1 = np.array([1,2,3])
print(a1.ndim)

1


In [38]:
a2 = np.array([[1,2,3],[4,5,6]])
print(a2.ndim)

2


In [39]:
a3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(a3.ndim)

3


In [43]:
a4 = a3.reshape([1,12])
print(a4)
print(a4.shape)
print(a4.ndim)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
(1, 12)
2


In [7]:
a5 = a3.reshape([12,])
print(a5)
print(a5.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [9]:
a5 = a3.flatten()
print(a5)
print(a5.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [11]:
#元素个数
count = a3.size
print(count)

12


In [12]:
#每一个元素占字节的大小
itemsize = a3.itemsize
print(itemsize)
print(a3.dtype)

4
int32


总结
1.
* 数组一般达到3维已经很复杂，不方便计算，所以一般会把3维以上的数组转换为2维数组
2.
* 通过ndarray.ndim可以看到数组的维度
3.
* 通过ndarray.shape可以看到数组的形状，shape是一个元祖，里面有几个元素代表几维数组
4.
* 通过ndarray.reshape可以修改数组的形状，条件只有一个，就是修改后的形状的元素个数必须和原来的个数一致
5.
* 通过ndarray.size可以看到数组一共有多少元素
6.
* 通过ndarray.itemsize可以看到数组中每个元素的所占内存的大小，单位是字节（1个字节=8位）

## 4）数组的索引和切片

In [13]:
import numpy as np

In [17]:
#1.一维数组的索引和切片
a1 = np.arange(10)
print(a1[4])
print(a1[4:6])
print(a1[:])
print(a1[::2])
print(a1[-1])

4
[4 5]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
9


In [23]:
#2.多维数组的索引和切片
#在中括号中，使用逗号进行分割，逗号前面是行，后面是列，如果只有一个值，那这个值就是行
a2 = np.random.randint(0,10,size=(4,6))
print(a2)

[[8 5 2 0 2 5]
 [2 7 2 1 8 8]
 [8 7 2 4 5 4]
 [3 6 3 0 0 5]]


In [24]:
a2[0]

array([8, 5, 2, 0, 2, 5])

In [25]:
a2[1:3]

array([[2, 7, 2, 1, 8, 8],
       [8, 7, 2, 4, 5, 4]])

In [27]:
a2[[0,2,3]]

array([[8, 5, 2, 0, 2, 5],
       [8, 7, 2, 4, 5, 4],
       [3, 6, 3, 0, 0, 5]])

In [28]:
a2[1,1]

7

In [29]:
a2[[1,2],[4,5]]

array([8, 4])

In [31]:
a2[(1,2),(4,5)]

array([8, 4])

In [32]:
a2[1:3,4:6]

array([[8, 8],
       [5, 4]])

In [33]:
a2[:,1]

array([5, 7, 7, 6])

总结
1.
* 如果数组是一维的，那么索引和切片就是跟python的列表是一样的
2.
* 如果是多维的（以二维为例），那么在中括号中，给两个值，两个值是通过逗号分隔的，逗号前面是行，逗号后面是列。如果括号中只有一个值，那么就是代表的行
3.
* 如果是多维数组（以二维为例），那么行的部分和列的部分，都遵循一维数组的方式，可以使用整形和切片，还可以使用中括号的形式来代表不连续行列。

## 5）布尔索引

In [44]:
import numpy as np

In [45]:
a2 = np.arange(24).reshape([4,6])

In [47]:
print(a2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [48]:
a2 < 10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [49]:
a2[a2<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a2[(a2<5)|(a2>10)]

array([ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23])

## 6）数组值的替换

In [51]:
import numpy as np

In [53]:
a3 = np.random.randint(0,10,size=(3,5))
a3

array([[6, 1, 6, 8, 5],
       [6, 3, 5, 2, 4],
       [9, 7, 1, 9, 1]])

In [56]:
#索引替换
a3[1] = 0
a3

array([[6, 1, 6, 8, 5],
       [0, 0, 0, 0, 0],
       [9, 7, 1, 9, 1]])

In [57]:
a3[1] = np.array([1,2,3,4,5])
a3

array([[6, 1, 6, 8, 5],
       [1, 2, 3, 4, 5],
       [9, 7, 1, 9, 1]])

In [59]:
#条件索引替换
a3[a3<3] = 1
a3

array([[6, 1, 6, 8, 5],
       [1, 1, 3, 4, 5],
       [9, 7, 1, 9, 1]])

In [62]:
#函数替换
result = np.where(a3<5,0,1)
result

array([[1, 0, 1, 1, 1],
       [0, 0, 0, 0, 1],
       [1, 1, 0, 1, 0]])

总结
1.
* 使用索引或者切片来替换
2.
* 利用条件索引来替换
3.
* 使用where函数来实现

## 7）数组的广播机制