import numpy as np

In [3]:
a = [1,2,3,'5']
a

[1, 2, 3, '5']

In [5]:
#numpy中的数组的数据类型一定要完全一致
b = np.array([4,5,'6'])
b

array(['4', '5', '6'], dtype='<U11')

In [6]:
c = np.array([4,5,6.0])
c

array([4., 5., 6.])

## 1）创建数组

In [7]:
#1.使用np.array
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [8]:
#2.使用np.arange,类似python中的range
b = np.arange(0,11,3)
b

array([0, 3, 6, 9])

In [9]:
#3.使用np.random模块
c = np.random.random()
c

0.26058517342632226

In [16]:
d = np.random.random((4,3)) #生成4行3列的随机数的数组
d

array([[0.46302205, 0.35649744, 0.13665015],
       [0.83948556, 0.31169902, 0.71760449],
       [0.01658788, 0.30431872, 0.99105665],
       [0.22189495, 0.94395695, 0.35095591]])

In [20]:
e = np.random.randint(0,100,size=(4,4))#生成4行4列的数组，值的范围0-100之间
e

array([[42, 28, 41, 72],
       [36, 69, 55, 51],
       [71, 69, 51, 92],
       [10, 27, 83, 67]])

In [21]:
#4.使用特殊函数生成

In [24]:
a1 = np.zeros((3,3))
a1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
a2 = np.ones((4,4))
a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
a3 = np.full((5,5),6)
a3

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [27]:
a4 = np.eye(7)
a4

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

总结
* 数组中的数据类型都是一致的
* 使用四种方法创建数组

## 2）数组数据类型dtype

In [1]:
import numpy as np

In [2]:
e = np.array([1,2,])
print(e)
print(e.dtype)

[1 2]
int32


In [3]:
f = np.array(['a','n'],dtype='U')
print(f)
print(f.dtype)

['a' 'n']
<U1


In [5]:
uf = f.astype('S')
print(uf)
print(uf.dtype)
print(f.dtype)

[b'a' b'n']
|S1
<U1


总结
* numpy基于C语言编写，所以有很多数据类型
* numpy为了考虑处理海量数据的性能，针对不同的数据给不同的数据类型，来节省内存空间，所以有不同的数据类型
* numpy数组的元素有多种数据类型
* 用ndarray.astype修改数据类型

## 3）多维数组

In [36]:
import numpy as np

In [37]:
a1 = np.array([1,2,3])
print(a1.ndim)

1


In [38]:
a2 = np.array([[1,2,3],[4,5,6]])
print(a2.ndim)

2


In [39]:
a3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(a3.ndim)

3


In [43]:
a4 = a3.reshape([1,12])
print(a4)
print(a4.shape)
print(a4.ndim)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
(1, 12)
2


In [7]:
a5 = a3.reshape([12,])
print(a5)
print(a5.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [9]:
a5 = a3.flatten()
print(a5)
print(a5.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [11]:
#元素个数
count = a3.size
print(count)

12


In [12]:
#每一个元素占字节的大小
itemsize = a3.itemsize
print(itemsize)
print(a3.dtype)

4
int32


总结
* 数组一般达到3维已经很复杂，不方便计算，所以一般会把3维以上的数组转换为2维数组
* 通过ndarray.ndim可以看到数组的维度
* 通过ndarray.shape可以看到数组的形状，shape是一个元祖，里面有几个元素代表几维数组
* 通过ndarray.reshape可以修改数组的形状，条件只有一个，就是修改后的形状的元素个数必须和原来的个数一致
* 通过ndarray.size可以看到数组一共有多少元素
* 通过ndarray.itemsize可以看到数组中每个元素的所占内存的大小，单位是字节（1个字节=8位）

## 4）数组的索引和切片

In [13]:
import numpy as np

In [17]:
#1.一维数组的索引和切片
a1 = np.arange(10)
print(a1[4])
print(a1[4:6])
print(a1[:])
print(a1[::2])
print(a1[-1])

4
[4 5]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
9


In [23]:
#2.多维数组的索引和切片
#在中括号中，使用逗号进行分割，逗号前面是行，后面是列，如果只有一个值，那这个值就是行
a2 = np.random.randint(0,10,size=(4,6))
print(a2)

[[8 5 2 0 2 5]
 [2 7 2 1 8 8]
 [8 7 2 4 5 4]
 [3 6 3 0 0 5]]


In [24]:
a2[0]

array([8, 5, 2, 0, 2, 5])

In [25]:
a2[1:3]

array([[2, 7, 2, 1, 8, 8],
       [8, 7, 2, 4, 5, 4]])

In [27]:
a2[[0,2,3]]

array([[8, 5, 2, 0, 2, 5],
       [8, 7, 2, 4, 5, 4],
       [3, 6, 3, 0, 0, 5]])

In [28]:
a2[1,1]

7

In [29]:
a2[[1,2],[4,5]]

array([8, 4])

In [31]:
a2[(1,2),(4,5)]

array([8, 4])

In [32]:
a2[1:3,4:6]

array([[8, 8],
       [5, 4]])

In [33]:
a2[:,1]

array([5, 7, 7, 6])

总结
* 如果数组是一维的，那么索引和切片就是跟python的列表是一样的
* 如果是多维的（以二维为例），那么在中括号中，给两个值，两个值是通过逗号分隔的，逗号前面是行，逗号后面是列。如果括号中只有一个值，那么就是代表的行
* 如果是多维数组（以二维为例），那么行的部分和列的部分，都遵循一维数组的方式，可以使用整形和切片，还可以使用中括号的形式来代表不连续行列。

## 5）布尔索引

In [44]:
import numpy as np

In [45]:
a2 = np.arange(24).reshape([4,6])

In [47]:
print(a2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [48]:
a2 < 10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [49]:
a2[a2<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a2[(a2<5)|(a2>10)]

array([ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23])

## 6）数组值的替换

In [51]:
import numpy as np

In [53]:
a3 = np.random.randint(0,10,size=(3,5))
a3

array([[6, 1, 6, 8, 5],
       [6, 3, 5, 2, 4],
       [9, 7, 1, 9, 1]])

In [56]:
#索引替换
a3[1] = 0
a3

array([[6, 1, 6, 8, 5],
       [0, 0, 0, 0, 0],
       [9, 7, 1, 9, 1]])

In [57]:
a3[1] = np.array([1,2,3,4,5])
a3

array([[6, 1, 6, 8, 5],
       [1, 2, 3, 4, 5],
       [9, 7, 1, 9, 1]])

In [59]:
#条件索引替换
a3[a3<3] = 1
a3

array([[6, 1, 6, 8, 5],
       [1, 1, 3, 4, 5],
       [9, 7, 1, 9, 1]])

In [62]:
#函数替换
result = np.where(a3<5,0,1)
result

array([[1, 0, 1, 1, 1],
       [0, 0, 0, 0, 1],
       [1, 1, 0, 1, 0]])

总结
* 使用索引或者切片来替换
* 利用条件索引来替换
* 使用where函数来实现

## 7）数组的广播机制

In [11]:
import numpy as np

In [12]:
a1 = np.random.randint(0,5,size=(3,5))

In [13]:
a1

array([[3, 1, 2, 2, 3],
       [2, 2, 2, 3, 1],
       [4, 2, 1, 1, 2]])

In [14]:
a1*2

array([[6, 2, 4, 4, 6],
       [4, 4, 4, 6, 2],
       [8, 4, 2, 2, 4]])

### 数组与数组的运算

1.结构相同的数组之间的运算

In [ ]:
a2 = np.random.randint(0,5,size=(3,5))

In [17]:
a2

array([[4, 4, 4, 3, 0],
       [1, 1, 3, 2, 0],
       [3, 2, 0, 0, 2]])

In [18]:
a1 + a2

array([[7, 5, 6, 5, 3],
       [3, 3, 5, 5, 1],
       [7, 4, 1, 1, 4]])

2.与行数相同且只有一列的数组之间的运算

In [23]:
a3 = np.random.randint(0,5,size=(3,4))

In [24]:
a3

array([[2, 4, 4, 1],
       [4, 1, 0, 3],
       [0, 4, 4, 0]])

In [25]:
a1+a3

ValueError: operands could not be broadcast together with shapes (3,5) (3,4) 

In [26]:
a4 = np.random.randint(0,5,size=(3,1))

In [28]:
a4

array([[2],
       [4],
       [4]])

In [27]:
a1+a4

array([[5, 3, 4, 4, 5],
       [6, 6, 6, 7, 5],
       [8, 6, 5, 5, 6]])

In [29]:
a1

array([[3, 1, 2, 2, 3],
       [2, 2, 2, 3, 1],
       [4, 2, 1, 1, 2]])

In [30]:
a5 = np.random.randint(0,5,size=(1,5))

In [31]:
a5

array([[2, 2, 4, 3, 1]])

In [32]:
print(a1)
print('='*30)
print(a5)

[[3 1 2 2 3]
 [2 2 2 3 1]
 [4 2 1 1 2]]
[[2 2 4 3 1]]


In [33]:
a1+a5

array([[5, 3, 6, 5, 4],
       [4, 4, 6, 6, 2],
       [6, 4, 5, 4, 3]])

总结
* 数组和数字可以直接运算
* shape相同数组可以直接运算
* shape不同数组运算，需要看是否满足广播原则（复杂）

## 8）数组形状的操作

### 1.reshape（不改变原数组）和resize（改变原数组）

In [34]:
import numpy as np

In [35]:
a1 = np.random.randint(0,10,size=(3,4))

In [36]:
a1

array([[6, 4, 8, 2],
       [1, 7, 4, 5],
       [5, 1, 7, 3]])

In [37]:
a1.reshape((2,6))

array([[6, 4, 8, 2, 1, 7],
       [4, 5, 5, 1, 7, 3]])

In [38]:
a1

array([[6, 4, 8, 2],
       [1, 7, 4, 5],
       [5, 1, 7, 3]])

In [39]:
a1.resize((2,6))

In [40]:
a1

array([[6, 4, 8, 2, 1, 7],
       [4, 5, 5, 1, 7, 3]])

### 2.flatten(返回的是拷贝，修改拷贝不影响原来的值）和ravel（返回的是view，修改view影响原来的值）

a2 =  np.random.randint(0,10,size=(3,4))

In [42]:
a2.flatten()

array([4, 5, 7, 8, 4, 3, 9, 8, 9, 9, 6, 0])

In [43]:
a2

array([[4, 5, 7, 8],
       [4, 3, 9, 8],
       [9, 9, 6, 0]])

In [44]:
a2.ravel()

array([4, 5, 7, 8, 4, 3, 9, 8, 9, 9, 6, 0])

In [45]:
a2

array([[4, 5, 7, 8],
       [4, 3, 9, 8],
       [9, 9, 6, 0]])

In [46]:
a3 = a2.flatten()

In [47]:
a3[0] = 100

In [48]:
a3

array([100,   5,   7,   8,   4,   3,   9,   8,   9,   9,   6,   0])

In [49]:
a2

array([[4, 5, 7, 8],
       [4, 3, 9, 8],
       [9, 9, 6, 0]])

In [50]:
a4 = a2.ravel()

In [51]:
a4[2] = 100

In [52]:
a4

array([  4,   5, 100,   8,   4,   3,   9,   8,   9,   9,   6,   0])

In [53]:
a2

array([[  4,   5, 100,   8],
       [  4,   3,   9,   8],
       [  9,   9,   6,   0]])

总结
* reshape和resize都是重新定义形状，reshape不会修改数组本身，但resize直接修改原数组
* flatten和ravel都是将原数组变成一维数组，它们都不会直接修改原数组。flatten返回一个原数组拷贝，修改拷贝不影响原数组，但ravel返回view，修改view会改变原数组

### 3.数组的叠加

In [55]:
vstack1 = np.random.randint(0,10,size=(3,4))

In [57]:
vstack1

array([[8, 7, 5, 5],
       [0, 2, 9, 3],
       [5, 3, 0, 3]])

In [56]:
vstack2 = np.random.randint(0,10,size=(2,4))

In [58]:
vstack2

array([[7, 3, 9, 0],
       [1, 8, 2, 6]])

In [59]:
vstack3 = np.vstack([vstack2,vstack1])

In [60]:
vstack3

array([[7, 3, 9, 0],
       [1, 8, 2, 6],
       [8, 7, 5, 5],
       [0, 2, 9, 3],
       [5, 3, 0, 3]])

In [61]:
hstack1 = np.random.randint(0,10,size=(3,4))

In [62]:
hstack1

array([[8, 2, 0, 9],
       [4, 6, 4, 9],
       [8, 5, 7, 7]])

In [63]:
hstack2 = np.random.randint(0,10,size=(3,6))

In [64]:
hstack2

array([[0, 9, 2, 4, 5, 9],
       [1, 8, 8, 3, 9, 3],
       [3, 4, 2, 2, 6, 8]])

In [65]:
hstack3 = np.hstack([hstack1,hstack2])

In [66]:
hstack3

array([[8, 2, 0, 9, 0, 9, 2, 4, 5, 9],
       [4, 6, 4, 9, 1, 8, 8, 3, 9, 3],
       [8, 5, 7, 7, 3, 4, 2, 2, 6, 8]])

In [69]:
vstack4 = np.concatenate([vstack2,vstack1],axis=0)

In [70]:
vstack4

array([[7, 3, 9, 0],
       [1, 8, 2, 6],
       [8, 7, 5, 5],
       [0, 2, 9, 3],
       [5, 3, 0, 3]])

In [71]:
hstack4 = np.concatenate([hstack1,hstack2],axis=1)

In [72]:
hstack4

array([[8, 2, 0, 9, 0, 9, 2, 4, 5, 9],
       [4, 6, 4, 9, 1, 8, 8, 3, 9, 3],
       [8, 5, 7, 7, 3, 4, 2, 2, 6, 8]])

In [73]:
hstack5 = np.concatenate([hstack1,hstack2],axis=None)

In [74]:
hstack5

array([8, 2, 0, 9, 4, 6, 4, 9, 8, 5, 7, 7, 0, 9, 2, 4, 5, 9, 1, 8, 8, 3,
       9, 3, 3, 4, 2, 2, 6, 8])

总结
* vstack在垂直方向叠加，hstack在水平方向叠加
* concatenate可以手动指定在哪个方向叠加，axis=0在垂直方向叠加，axis=1在水平方向叠加，axis=None表示在可以进行的方向叠加，然后扁平化

### 4.数组的切割

In [1]:
import numpy as np

In [2]:
hs1 = np.random.randint(0,5,size=(3,4))

In [3]:
hs1

array([[0, 4, 2, 0],
       [2, 4, 4, 2],
       [3, 2, 1, 0]])

In [4]:
np.hsplit(hs1,2)

[array([[0, 4],
        [2, 4],
        [3, 2]]),
 array([[2, 0],
        [4, 2],
        [1, 0]])]

In [5]:
np.hsplit(hs1,[1,3])

[array([[0],
        [2],
        [3]]),
 array([[4, 2],
        [4, 4],
        [2, 1]]),
 array([[0],
        [2],
        [0]])]

In [6]:
vs1 = np.random.randint(0,10,size=(6,3))

In [7]:
vs1

array([[6, 8, 8],
       [8, 8, 5],
       [0, 3, 1],
       [3, 9, 6],
       [7, 3, 2],
       [7, 4, 3]])

In [9]:
np.vsplit(vs1,3)

[array([[6, 8, 8],
        [8, 8, 5]]),
 array([[0, 3, 1],
        [3, 9, 6]]),
 array([[7, 3, 2],
        [7, 4, 3]])]

In [10]:
np.vsplit(vs1,[2,4,5])

[array([[6, 8, 8],
        [8, 8, 5]]),
 array([[0, 3, 1],
        [3, 9, 6]]),
 array([[7, 3, 2]]),
 array([[7, 4, 3]])]

总结
* hsplit在水平方向切割，vsplit在垂直方向切割
* 第一种是平均切割，第二种是指定下标切割

### 5.数组的转置

In [11]:
import numpy as np

In [12]:
t1 = np.random.randint(0,20,size=(3,4))

In [13]:
t1

array([[ 0, 18,  1,  5],
       [12, 19,  5, 11],
       [18,  9, 11, 18]])

In [14]:
t1.T

array([[ 0, 12, 18],
       [18, 19,  9],
       [ 1,  5, 11],
       [ 5, 11, 18]])

In [15]:
t1.dot(t1.T)

array([[350, 402, 263],
       [402, 651, 640],
       [263, 640, 850]])

In [17]:
t1.transpose()#返回的是view

array([[ 0, 12, 18],
       [18, 19,  9],
       [ 1,  5, 11],
       [ 5, 11, 18]])

In [18]:
t2=t1.transpose()

In [19]:
t2[0] = 100

In [20]:
t2

array([[100, 100, 100],
       [ 18,  19,   9],
       [  1,   5,  11],
       [  5,  11,  18]])

In [21]:
t1

array([[100,  18,   1,   5],
       [100,  19,   5,  11],
       [100,   9,  11,  18]])

总结
* 可以通过ndarray.T的形式进行专职
* 可以通过ndarray.transpose()进行转置，这个方法返回的是一个view

### 6.深拷贝和浅拷贝

In [22]:
import numpy as np

In [23]:
#不拷贝
a = np.arange(10)
b = a
print(b is a)

True


In [26]:
#view或者浅拷贝，只拷贝栈区，但堆区指向一致
a = np.arange(11)

In [27]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
c = a.view()

In [29]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
c[0] = 3

In [31]:
c

array([ 3,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
a

array([ 3,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
#深拷贝，栈区和堆区都拷贝
a = np.arange(14)

In [36]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [37]:
c = a.copy()

In [38]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [39]:
c[0] = 100

In [40]:
c

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13])

In [41]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

## 8）文件操作

### 1.保存文件

In [1]:
import numpy as np


In [5]:
score = np.random.randint(11,23,size=(3,4))

In [6]:
score

array([[20, 20, 12, 18],
       [13, 12, 12, 20],
       [12, 11, 17, 15]])

In [4]:
help(np.savetxt)

Help on function savetxt in module numpy:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
    
        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e %+.4ej %.4

In [9]:
np.savetxt('score.csv',score,delimiter=',',header='1,2,3',comments='')

In [10]:
np.savetxt('score2.csv',score,delimiter=',',header='1,2,3',comments='',fmt='%d')

### 2.读取文件

In [15]:
np.loadtxt('score.csv',dtype=np.int32,delimiter=',',skiprows=1)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_6440\3386699932.py:1: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  np.loadtxt('score.csv',dtype=np.int32,delimiter=',',skiprows=1)


array([[20, 20, 12, 18],
       [13, 12, 12, 20],
       [12, 11, 17, 15]])

### 3.np独有的存储解决方案

In [16]:
c = np.random.randint(10,20,size=(2,3))

In [17]:
np.save('c',c)

In [19]:
np.load('c.npy')

array([[15, 17, 16],
       [11, 16, 10]])

In [21]:
##该方法可以保存多维数组
d = np.random.randint(10,20,size=(2,3,4))

In [22]:
d

array([[[19, 19, 14, 10],
        [15, 19, 11, 18],
        [12, 12, 11, 10]],

       [[13, 10, 13, 11],
        [12, 14, 17, 11],
        [12, 11, 12, 17]]])

In [23]:
np.savetext('d.csv',d)

AttributeError: module 'numpy' has no attribute 'savetext'

In [24]:
np.save('d',d)

In [26]:
np.load('d.npy')

array([[[19, 19, 14, 10],
        [15, 19, 11, 18],
        [12, 12, 11, 10]],

       [[13, 10, 13, 11],
        [12, 14, 17, 11],
        [12, 11, 12, 17]]])

总结：
* np.savetxt和np.loadtxt一般用来操作csv文件，可以设置header，但不能存储3维以上的数组
* np.save和np.load一般用来存储非文本类型文件，不可以设置header，但可以存储3维以上数组

## NAN和INF值处理

* NAN不是一个数字，但属于浮点类型
* INF表示无穷大，可以正无穷也可以负无穷

In [53]:
import numpy as np

In [28]:
data = np.random.randint(0,10,size=(3,5))
data

array([[5, 5, 0, 4, 8],
       [6, 2, 1, 6, 3],
       [2, 8, 2, 9, 7]])

In [29]:
data[0,1] = np.NAN#必须是浮点类型才行

ValueError: cannot convert float NaN to integer

In [32]:
data = data.astype(np.float64)
data[0,1] = np.NAN

In [33]:
data

array([[ 5., nan,  0.,  4.,  8.],
       [ 6.,  2.,  1.,  6.,  3.],
       [ 2.,  8.,  2.,  9.,  7.]])

In [34]:
data/0

C:\Users\Administrator\AppData\Local\Temp\ipykernel_6440\1771165735.py:1: RuntimeWarning: divide by zero encountered in divide
  data/0
C:\Users\Administrator\AppData\Local\Temp\ipykernel_6440\1771165735.py:1: RuntimeWarning: invalid value encountered in divide
  data/0


array([[inf, nan, nan, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

nan和nan不相等

In [37]:
np.NAN == np.NAN

False

In [38]:
data[0,1]*2

nan

### 删除缺失值

In [39]:
data

array([[ 5., nan,  0.,  4.,  8.],
       [ 6.,  2.,  1.,  6.,  3.],
       [ 2.,  8.,  2.,  9.,  7.]])

In [40]:
data[1,2] = np.NAN
data

array([[ 5., nan,  0.,  4.,  8.],
       [ 6.,  2., nan,  6.,  3.],
       [ 2.,  8.,  2.,  9.,  7.]])

In [42]:
##所有NAN删除
np.isnan(data)

array([[False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False]])

In [45]:
data[~np.isnan(data)]#变成一维数组

array([5., 0., 4., 8., 6., 2., 6., 3., 2., 8., 2., 9., 7.])

In [51]:
##删除nan所在的行
lines = np.where(np.isnan(data))[0]#返回索引，以元组形式

In [52]:
np.delete(data,lines,axis=0)

array([[2., 8., 2., 9., 7.]])

### 用其他值进行替代

In [80]:
scores = np.loadtxt('nan_scores.csv',delimiter=',',skiprows=1,dtype=np.str_)
scores

array([['59', '89'],
       ['90', '32'],
       ['78', '45'],
       ['34', ''],
       ['', '56'],
       ['23', '56']], dtype='<U2')

In [83]:
scores = scores.astype(dtype='<U4') ##注意长度

In [85]:
scores.astype(np.float64)

ValueError: could not convert string to float: ''

In [86]:
scores[scores == ''] = np.nan

In [87]:
scores

array([['59', '89'],
       ['90', '32'],
       ['78', '45'],
       ['34', 'nan'],
       ['nan', '56'],
       ['23', '56']], dtype='<U4')

In [89]:
scores1 = scores.astype(np.float64)

In [90]:
scores1

array([[59., 89.],
       [90., 32.],
       [78., 45.],
       [34., nan],
       [nan, 56.],
       [23., 56.]])

In [91]:
scores1[np.isnan(scores1)] = 0

In [93]:
scores1.sum()

562.0

In [94]:
scores1.sum(axis=1)

array([148., 122., 123.,  34.,  56.,  79.])

In [98]:
scores2 = scores.astype(np.float64)
scores2

array([[59., 89.],
       [90., 32.],
       [78., 45.],
       [34., nan],
       [nan, 56.],
       [23., 56.]])

In [100]:
scores2.shape[1]

2

In [109]:
for x in range(scores2.shape[1]):
    col = scores2[:,x]
    non_nan_col = col[~np.isnan(col)]
    mean = non_nan_col.mean()
    col[np.isnan(col)] = mean
scores2


array([[59. , 89. ],
       [90. , 32. ],
       [78. , 45. ],
       [34. , 55.6],
       [56.8, 56. ],
       [23. , 56. ]])

In [114]:
scores2.sum(axis=1)

array([148. , 122. , 123. ,  89.6, 112.8,  79. ])

总结：
* NAN代表的是not a number，不是一个数字，但它属于浮点类型
* INF：无穷大
* NAN和所有的值进行运算都是NAN
* NAN不等于NAN
* 可以通过np.isnan判断某个值是不是NAN
* 处理值，可以通过删除或者替换的方式处理

## 各种模块和函数

### 1.np.random模块

In [1]:
import numpy as np

In [14]:
np.random.seed(1) ###固定时间戳，使rand函数产生的值不管运行多少次都是固定值
np.random.rand()

0.417022004702574

In [16]:
np.random.rand(1,3,4) ##指定维度

array([[[0.87811744, 0.02738759, 0.67046751, 0.4173048 ],
        [0.55868983, 0.14038694, 0.19810149, 0.80074457],
        [0.96826158, 0.31342418, 0.69232262, 0.87638915]]])

In [18]:
np.random.randn(2,3)  ##标准正态分布

array([[-0.85005238,  0.96082   , -0.21741818],
       [ 0.15851488,  0.87341823, -0.11138337]])

In [20]:
np.random.randint(10,40,size=(2,3))  ##指定区间的整型随机数

array([[35, 29, 16],
       [18, 10, 12]])

In [23]:
data = np.arange(10)
np.random.choice(data,size=(3,4))  ##只能数据中选择数

array([[7, 7, 9, 7],
       [3, 0, 8, 7],
       [7, 1, 1, 3]])

In [26]:
data1 = np.arange(11)
np.random.shuffle(data1)  ##随机打乱数字
data1

array([ 3,  2,  0,  1, 10,  5,  9,  6,  4,  8,  7])